language: bash
services:
- docker
sudo: required
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t koretskyhub/front:nginx .
- docker push koretskyhub/front:nginx
- ssh-keyscan -H 95.163.212.32 >> ~/.ssh/known_hosts
- chmod 400 2018_2_42_id_rsa.pem
- ssh ubuntu@95.163.212.32 -i './2018_2_42_id_rsa.pem' 'sudo docker pull koretskyhub/front:nginx'
- ssh ubuntu@95.163.212.32 -i './2018_2_42_id_rsa.pem' 'sudo docker run koretskyhub/front:nginx'
before_install:
- openssl aes-256-cbc -K $encrypted_ec91d67f14aa_key -iv $encrypted_ec91d67f14aa_iv
  -in 2018_2_42_id_rsa.pem.enc -out ./2018_2_42_id_rsa.pem -d